#!/bin/bash
# POLYGOTTEM Launch Script
# Activates virtual environment and runs the application

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
VENV_DIR="venv"
MAIN_SCRIPT="polygottem.py"
CONFIG_DIR="$HOME/.polygottem"
CONFIG_FILE="$CONFIG_DIR/launch.conf"

# Print colored message
print_msg() {
    local color=$1
    shift
    echo -e "${color}$@${NC}"
}

# Check if virtual environment exists
if [ ! -d "$VENV_DIR" ]; then
    print_msg "$RED" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    print_msg "$RED" "  ERROR: Virtual environment not found!"
    print_msg "$RED" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    print_msg "$YELLOW" "Please run the installer first:"
    print_msg "$YELLOW" "  ./install.sh"
    echo
    print_msg "$YELLOW" "Or for Intel Meteor Lake optimization:"
    print_msg "$YELLOW" "  ./install.sh --intel"
    echo
    exit 1
fi

# Check if main script exists
if [ ! -f "$MAIN_SCRIPT" ]; then
    print_msg "$RED" "ERROR: $MAIN_SCRIPT not found!"
    exit 1
fi

# Activate virtual environment
source "$VENV_DIR/bin/activate"

# Initialize defaults
BENCHMARK=false
SHOW_HELP=false
SET_INTERACTIVE=false
SET_INTEL=false
CLEAR_CONFIG=false
SHOW_CONFIG=false

# Set default launch preferences (will be overridden by config file if it exists)
LAUNCH_MODE="interactive"
HARDWARE_ACCEL="intel"

# Load saved configuration if it exists
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE" 2>/dev/null || true
fi

# Handle special flags
for arg in "$@"; do
    case $arg in
        --benchmark)
            BENCHMARK=true
            shift
            ;;
        --help|-h)
            SHOW_HELP=true
            shift
            ;;
        --set-interactive)
            SET_INTERACTIVE=true
            shift
            ;;
        --set-intel)
            SET_INTEL=true
            shift
            ;;
        --clear-config)
            CLEAR_CONFIG=true
            shift
            ;;
        --show-config)
            SHOW_CONFIG=true
            shift
            ;;
    esac
done

# Handle configuration commands
if [ "$CLEAR_CONFIG" = true ]; then
    rm -f "$CONFIG_FILE"
    print_msg "$GREEN" "Configuration cleared"
    exit 0
fi

if [ "$SHOW_CONFIG" = true ]; then
    echo "POLYGOTTEM Launch Configuration"
    echo "================================"
    if [ -f "$CONFIG_FILE" ]; then
        cat "$CONFIG_FILE"
    else
        echo "No configuration saved (using defaults)"
    fi
    exit 0
fi

# Save configuration if requested
if [ "$SET_INTERACTIVE" = true ] || [ "$SET_INTEL" = true ]; then
    mkdir -p "$CONFIG_DIR"

    # Read current config or create new
    LAUNCH_MODE="tui"
    HARDWARE_ACCEL="none"

    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE" 2>/dev/null || true
    fi

    if [ "$SET_INTERACTIVE" = true ]; then
        LAUNCH_MODE="interactive"
        print_msg "$GREEN" "✓ Set launch mode to: interactive"
    fi

    if [ "$SET_INTEL" = true ]; then
        HARDWARE_ACCEL="intel"
        print_msg "$GREEN" "✓ Set hardware acceleration to: intel"
    fi

    # Save configuration
    cat > "$CONFIG_FILE" << EOF
# POLYGOTTEM Launch Configuration
# Auto-generated by launch.sh

LAUNCH_MODE="$LAUNCH_MODE"
HARDWARE_ACCEL="$HARDWARE_ACCEL"
EOF

    print_msg "$BLUE" "Configuration saved to: $CONFIG_FILE"
    echo
fi

# Run benchmark tests
if [ "$BENCHMARK" = true ]; then
    print_msg "$BLUE" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    print_msg "$BLUE" "  Running POLYGOTTEM Benchmark Tests"
    print_msg "$BLUE" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo

    # Check if benchmark tools exist
    if [ -f "tools/intel_acceleration.py" ]; then
        print_msg "$YELLOW" "Checking hardware acceleration..."
        python3 tools/intel_acceleration.py || true
        echo
    fi

    if [ -f "tools/exploit_header_generator.py" ]; then
        print_msg "$YELLOW" "Benchmarking exploit header generator..."
        python3 tools/exploit_header_generator.py --benchmark || true
        echo
    fi

    if [ -f "tools/multi_cve_polyglot.py" ]; then
        print_msg "$YELLOW" "Benchmarking multi-CVE polyglot generator..."
        python3 tools/multi_cve_polyglot.py --benchmark || true
        echo
    fi

    print_msg "$GREEN" "Benchmark tests completed!"
    exit 0
fi

# Show help
if [ "$SHOW_HELP" = true ]; then
    print_msg "$BLUE" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    print_msg "$BLUE" "  POLYGOTTEM - Polyglot Exploit Generator"
    print_msg "$BLUE" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    print_msg "$GREEN" "Usage:"
    print_msg "$GREEN" "  ./launch.sh [options]"
    echo
    print_msg "$YELLOW" "Launch Options:"
    print_msg "$YELLOW" "  --help, -h              Show this help message"
    print_msg "$YELLOW" "  --benchmark             Run benchmark tests"
    echo
    print_msg "$YELLOW" "Configuration Options:"
    print_msg "$YELLOW" "  --set-interactive       Set default launch mode to interactive"
    print_msg "$YELLOW" "  --set-intel             Set default hardware acceleration to Intel"
    print_msg "$YELLOW" "  --show-config           Display current configuration"
    print_msg "$YELLOW" "  --clear-config          Reset configuration to defaults"
    echo
    print_msg "$YELLOW" "Examples:"
    print_msg "$YELLOW" "  ./launch.sh                           # Launch POLYGOTTEM TUI"
    print_msg "$YELLOW" "  ./launch.sh --set-interactive         # Set interactive mode default"
    print_msg "$YELLOW" "  ./launch.sh --set-intel               # Enable Intel acceleration"
    print_msg "$YELLOW" "  ./launch.sh --set-interactive --set-intel  # Set both defaults"
    print_msg "$YELLOW" "  ./launch.sh --show-config             # View current settings"
    print_msg "$YELLOW" "  ./launch.sh --clear-config            # Reset to defaults"
    print_msg "$YELLOW" "  ./launch.sh --benchmark               # Run performance tests"
    echo
    print_msg "$BLUE" "Documentation:"
    print_msg "$BLUE" "  See docs/guides/ for detailed documentation"
    echo
    exit 0
fi

# Launch the main application
print_msg "$BLUE" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
print_msg "$BLUE" "  Launching POLYGOTTEM..."
print_msg "$BLUE" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

# Run the main script with all remaining arguments
python3 "$MAIN_SCRIPT" "$@"
